name: director
listen: "{{HOST|default('0.0.0.0')}}:{{PORT|default(8080)}}"
env: "{{ENV}}"
redis_dsn: "{{REDIS_DSN|default('redis://redis:6379')}}"
ch_dsn: "{{CHP_DSN|default('http://default:default@host:9090')}}"
data_dir: "{{DATA_DIR|default('/data')}}"
# initial
initial_startup: {{INITIAL_STARTUP|default('[]')}}

images:
  - prefix: rockstat/band-
    collection: true
    path: "{{IMAGES_PATH|default('/images')}}/band_set"
  - prefix: rockstat/user-
    collection: true
    path: "{{IMAGES_PATH|default('/images')}}/user"
  - prefix: rockstat/rockme-
    collection: true
    path: "{{IMAGES_PATH|default('/images')}}/rockme_set"

# following params will be paseed to image and container builder functions
container_params:
  network: "{{NETWORK|default('custom')}}"
  memory: 367001600 # limit 350mb
  bind_ip: "{{BIND_HOST_IP|default('0.0.0.0')}}"
  env: {{ENCODED_ENV}}
  etc_hosts:
    host: "{{HOST_ADDR|default('172.17.0.1')}}"
  